
import { ReactNode } from 'react';
import type { Metadata } from 'next'
import { FormDataProvider } from "@/app/hooks/useFormDataContext";
import './globals.css'

export const metadata: Metadata = {
  title: 'Send Relatory',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactNode,
}

export default function RootLayout({children}:RootLayoutProps) {
  return (
    <html lang="en">
      <body id="root" className='w-screen h-screen flex bg-primary-shape'>
        <FormDataProvider>
          {children}
        </FormDataProvider>
      </body>
    </html>
  )
}
